language: ruby
rvm:
  - 2.3.3

before_script:
  - chmod +x ./script/cibuild

# script: ./script/cibuild

notifications:
  email: ellusionistanh@gmail.com

# branch whitelist, only for GitHub Pages
branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
